### ISSUE TITLE
Line length linter yells at comments?

### ISSUE THREAD

**Issue by Vighnesh-V** [upenn-cis1xx/camelot#55]
**Describe the bug**
The code for line length checking flags commented lines exceeding 80 characters as a style violation.

**To Reproduce**
From the main directory run:
`dune exec -- bin/camelot.exe -f test/examples/verbose.ml`

**Expected behavior**
Unclear what expected behaviour is - should we flag this? @Zdancewic @KeenWill @dlike230 @swapneelsheth.

If this is an error we can address, might be an interesting dev project? We could toggle it via a linter flag / fix the actual linting code to not flag this as an style problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/22487100/91739299-ba77aa80-eb7f-11ea-99f9-8b1e0da02bc2.png)

**Desktop (please complete the following information):**
- WSL

**Comment by dlike230** [comment]
I feel like we should keep this rule for comments too. Having long comments that you need to scroll sideways to see sometimes leads to bad readability.

**Comment by KeenWill** [comment]
Agree with Dan. All lines should obey the 80 (or 100 for Java) limit for readability

**Comment by KeenWill** [comment]
Closing for now. We can reopen later if this is a thing we actually want changed.
