### ISSUE TITLE
Just a note to @Vighnesh-V

### ISSUE THREAD

**Issue by Vighnesh-V** [upenn-cis1xx/camelot#80]
Rewrite camelot config lang to be waaaaay simpler. Maybe use yaml/toml?

Add new config options, e.g include / exclude, arguments to linting functions (e.g. disabling certain modules etc...)

Add option to 'check' a config file to verify that it is well formed ...

**Comment by KeenWill** [comment]
yaml >>> toml imo

**Comment by Vighnesh-V** [comment]
In progress
